name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_VERSION: latest
  DOCKER_SWARM_PROJECT: kirsh-wheel
  GITHUB_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: kirshway/kirsh-wheel

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}:${{ env.DOCKER_IMAGE_VERSION }}

  deploy:
    runs-on: ubuntu-24.04

    needs: [build]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Deploy 🚀
        run: |
          env DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          env NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" \
          env NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" \
          env AUTH_TRUST_HOST="${{ secrets.AUTH_TRUST_HOST }}" \
          env POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
          env VERSION="${{ env.DOCKER_IMAGE_VERSION }}" \
            docker stack deploy --prune --with-registry-auth -c docker-compose.yml ${{ env.DOCKER_SWARM_PROJECT }}
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 